### ISSUE TITLE
Implement limits and offset for GET which sends back lists

### ISSUE THREAD

**Issue by gnagar** [bigdroptech/square1#31]
All GET operations sending list of entities back should have constraints and filters in place to ensure we do not end up eating all server resources to collect data for a huge number of entities. These are:
    a. accept limit parameter to limit the number of records returend by the API
    b. accept offset parameter to specify which page needs to be sent. The first offset should be clearly documented (is it 0 or 1) - in our case I suggest to keep it as 0
    c. Put a hard limit on the max number of records which will be sent regardless of limit value (suggested value is 100)
    d. limit and offset need to be query params
    e. The above should be consistent across get operations

    e.g. for total of 105 records:
    https://url/api/v1/endpoint?limit=10&offset=0: send items 1-10
    https://url/api/v1/endpoint: send items 1-100
    https://url/api/v1/endpoint?limit=10&offset=10: send items 101-105
    https://url/api/v1/endpoint?limit=10&offset=11: send 404 (Not found)
    https://url/api/v1/endpoint?limit=200&offset=1: send 404 (Not found)
    https://url/api/v1/endpoint?limit=200&offset=0: send items 1-100
    https://url/api/v1/endpoint?limit=200&offset=1: send items 101-105
    https://url/api/v1/endpoint?limit=100&offset=1: send items 101-105

**Comment by navidkhn1** [comment]
This has been done.
