### ISSUE TITLE
Secrets to be loaded from a file

### ISSUE THREAD

**Issue by gnagar** [bigdroptech/square1#81]
All secrets and environmental values will need to be sourced from a file the path to which will be provided in another environment variable. This is essential for container based deployment where secrets are injected as file. The file can be injected as a .py file which can contain the variables and values in:

KEY1=VALUE1
KEY2=VALUE2

format (if that helps). The name of the environment variable containing the absolute path to the file containing these KEY VALUE pairs will be SQUARE1_SECRETS_FILE

**Comment by navidkhn1** [comment]
Hey @gnagar , this is already being done is it not? We have a secrets.py file. Will that not work?
